from typing import Any, Union

class Color:
    r: Any
    g: Any
    b: Any
    def __init__(self, c: Union[str, int]) -> None: ...
    def __eq__(self, other): ...
    @property
    def rbg(self): ...
    @property
    def hex(self): ...
