from ..core.dispatch import GatewayDispatch as GatewayDispatch
from ..objects.events.channel import ChannelPinsUpdateEvent as ChannelPinsUpdateEvent

async def channel_pins_update_middleware(self, payload: GatewayDispatch): ...
def export(): ...
