from ..core.dispatch import GatewayDispatch as GatewayDispatch
from ..objects.guild import Guild as Guild
from ..utils.conversion import construct_client_dict as construct_client_dict

async def guild_create_middleware(self, payload: GatewayDispatch): ...
def export(): ...
