from enum import Enum
from typing import Any

class GuildFeature(Enum):
    ANIMATED_ICON: Any
    BANNER: Any
    COMMERCE: Any
    COMMUNITY: Any
    DISCOVERABLE: Any
    FEATURABLE: Any
    INVITE_SPLASH: Any
    MEMBER_VERIFICATION_GATE_ENABLED: Any
    NEWS: Any
    PARTNERED: Any
    PREVIEW_ENABLED: Any
    VANITY_URL: Any
    VERIFIED: Any
    VIP_REGIONS: Any
    WELCOME_SCREEN_ENABLED: Any
    TICKETED_EVENTS_ENABLED: Any
    MONETIZATION_ENABLED: Any
    MORE_STICKERS: Any
    THREE_DAY_THREAD_ARCHIVE: Any
    SEVEN_DAY_THREAD_ARCHIVE: Any
    PRIVATE_THREADS: Any
    NEW_THREAD_PERMISSIONS: Any
