name: Workflow for Codecov
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dependencies (dev)
        run: pip install -r requirements_dev.txt
      - name: Run tests and collect coverage
        run: |
          pytest --cov=./tests
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
