name: Run Scripts

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

        with:
          python-version: "3.8"
          architecture: "x64"

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@pincer.dev"
          git pull

      - name: running all sorter
        run: |
          python ./.github/scripts/all_sorter.py
          git commit -am ":art: Automatic `__all__` sorting" || echo "No changes to commit"
          git push || echo "No changes to push"


      - name: running license generator
        run: |
          python ./.github/scripts/license_generator.py
          git commit -am ":page_facing_up: Automatic license generator" || echo "No changes to commit"
          git push || echo "No changes to push"
