name: Generate setup.cfg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

        with:
          persist-credentials: false
          fetch-depth: 0
          python-version: '3.8'
          architecture: 'x64'

      - name: install requirements
        run: pip install -r requirements.txt

      - name: install pincer
        run: pip install -e .

      - name: generate setup.cfg
        run: python -u setup_config/generator.py

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@pincer.dev"

      - name: add to git
        run: |
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -m ":hammer: Automatic update of setup.cfg"
          git push origin main
